import Link from 'next/link';
import PageEntrance from '@/components/PageEntrance';
import Image from 'next/image';
import '../placeholder-details.css';
import {Header,Footer} from '@/components/SiteChrome';
import Gallery from './Gallery';
import './detalhe.css';
const img=(n:string)=>`/images/tela4-img${n}.svg`;
const itinerary=[['17h00','Encontro em Qaitbay','Recepção no terminal marítimo e travessia até a ilha.'],['17h30','Galerias históricas','Visita guiada às coleções e à reconstrução.'],['18h30','Câmara da Luz','Demonstração sobre óptica e navegação antiga.'],['19h00','Mirante e degustação','Pôr do sol, sabores mediterrâneos e acendimento da luz.'],['20h00','Retorno','Descida assistida e travessia ao continente.']];
const included=['Travessia marítima de ida e volta','Entrada e percurso guiado completo','Acesso reservado ao mirante','Degustação mediterrânea','Bebidas não alcoólicas','Audioguia complementar','Lembrança exclusiva da experiência','Equipe de acessibilidade mediante solicitação'];
const details=[['Horários','Saídas variáveis entre 16h30 e 18h, conforme a estação.'],['Duração','Aproximadamente 3 horas, incluindo as travessias.'],['Regras','Chegada com 30 minutos de antecedência. Menores acompanhados por responsável.'],['Clima','Em condições marítimas adversas, a experiência poderá ser reagendada.'],['Acessibilidade','Elevadores em todo o percurso. Mirante acessível e apoio disponível mediante solicitação.'],['Cancelamento','Reembolso integral ou alteração sem custo até 48 horas antes.']];
export default function Detail(){return <PageEntrance><main className="detail-page"><Header/><section className="detail-hero"><img className="detail-texture" src={img('BackgroundTextureReusoExploreOFarol')} alt=""/><div className="detail-wrap"><div className="detail-hero-copy"><h1>Pharos ao<br/>Pôr do Sol.</h1><p>Suba enquanto Alexandria muda de cor e permaneça no mirante quando a nova luz de Pharos encontra o Mediterrâneo.</p><div className="detail-metadata">3 horas · Grupos de até 12 · A partir de €89</div><a className="button button-large" href="#datas">Escolher data →</a></div><Gallery/></div></section>
<section className="detail-description detail-light"><div className="detail-wrap"><span className="detail-label">02 · A experiência</span><h2>Uma noite entre história, sabores e horizonte.</h2><div className="detail-description-grid"><p>O percurso começa nas galerias ao fim da tarde, segue pela Câmara da Luz e termina no mirante reservado. Ali, um guia apresenta a relação entre astronomia e navegação enquanto o grupo desfruta uma seleção de sabores mediterrâneos.</p><div>{[['Mirante reservado','Acesso em grupo reduzido após o horário regular.'],['Guia especializado','História, navegação e arquitetura durante todo o percurso.'],['Mesa mediterrânea','Degustação inspirada nas culturas que atravessaram Alexandria.']].map(([t,p])=><article key={t}><h3>{t}</h3><p>{p}</p></article>)}</div></div></div></section>
<section className="detail-route"><div className="detail-route-textures" aria-hidden="true">{["Group4","Group5","Group6"].map(name=><img key={name} src={img(name)} alt=""/>)}</div><div className="detail-wrap"><span className="detail-label">03 · Roteiro</span><h2>Da pedra à luz.</h2><ol className="detail-itinerary">{itinerary.map(([time,title,copy])=><li key={time}><time>{time}</time><h3>{title}</h3><p>{copy}</p></li>)}</ol></div></section>
<section className="detail-inclusions detail-light"><div className="detail-wrap"><span className="detail-label">04 · O que está incluído</span><h2>Tudo preparado para uma noite memorável.</h2><ul className="detail-included">{included.map(t=><li key={t}><span aria-hidden="true">●</span>{t}</li>)}</ul></div></section>
<section className="detail-important"><img className="detail-texture" src={img("BackgroundTextureReusoExperiencias")} alt="" aria-hidden="true"/><div className="detail-wrap"><span className="detail-label">05 · Informações importantes</span><h2>Antes de subir.</h2><div className="detail-info-grid">{details.map(([t,p])=><article key={t}><h3>{t}</h3><p>{p}</p></article>)}</div></div></section>
<section className="detail-ending detail-light" id="datas"><div className="detail-ending-photo experience-ending-photo"><Image src="/images/pharos-por-do-sol-card-v2.webp" alt="Mirante de Pharos com degustação e vista do Mediterrâneo ao anoitecer" fill sizes="(max-width:767px) 100vw, 45vw" style={{objectFit:"cover"}}/></div><div className="detail-wrap"><span className="detail-label">06 · Reserva</span><h2>Escolha quando a luz encontrará você.</h2><p>Continue para escolher sua data, participantes e adicionais.</p><Link className="button button-large" href="/reserva/data?experiencia=pharos-por-do-sol">Continuar reserva →</Link></div><Footer light/></section></main></PageEntrance>}
