import Link from 'next/link';
import {ArrowRight} from 'lucide-react';
import PageEntrance from '@/components/PageEntrance';
import {Header,Footer} from '@/components/SiteChrome';
import './experiencias.css';
const image=(name:string,svg=false)=>name==='PlaceholderVisitaEssencial'?'/images/visita-essencial-card-v2.webp':name==='PlaceholderPharosAoPorDoSol'?'/images/pharos-por-do-sol-card-v2.webp':name==='PlaceholderJornadaHistorica'?'/images/jornada-historica-card-v2.webp':`/images/tela3-img${name}.${svg?'svg':'webp'}`;
const packages=[['Visita essencial','PlaceholderVisitaEssencial','O percurso fundamental pelas galerias, exposição histórica com audioguia e acesso ao mirante.','1h30 · Todos os públicos','29'],['Jornada histórica','PlaceholderJornadaHistorica','Galerias e coleções com guia, áreas especiais e demonstração antes da subida ao mirante.','2h30 · Apaixonados por história','49'],['Pharos ao pôr do sol','PlaceholderPharosAoPorDoSol','Subida guiada, gastronomia mediterrânea, iluminação noturna e experiência exclusiva no mirante.','3h · Casais e grupos','89']];
const rows=[['Galerias e exposição','●','●','●'],['Audioguia','●','●','●'],['Guia especializado','—','●','●'],['Áreas especiais','—','●','●'],['Gastronomia mediterrânea','—','—','●'],['Mirante ao entardecer','—','—','●']];
const information=[['Horários','Essencial: 09h–18h\nHistórica: 10h e 15h\nPôr do Sol: conforme a estação'],['Disponibilidade','Vagas diárias limitadas.\nReservas antecipadas recomendadas.'],['Acessibilidade','Percurso essencial integralmente acessível. Consulte condições das áreas especiais.'],['Cancelamento','Alterações gratuitas até 48 horas antes da visita.'],['Idiomas','Árabe, inglês, francês e português. Audioguia em 12 idiomas.'],['Ponto de encontro','Terminal marítimo de Qaitbay, 30 minutos antes do horário.']];
function Texture({name}:{name:string}){return <img className="xp-texture" src={image(name,true)} alt="" aria-hidden="true"/>}
export default function Experiences(){return <PageEntrance><main className="xp-page"><Header/><section className="xp-hero"><div className="xp-hero-textures" aria-hidden="true">{["Group","Group1","Group2"].map(name=><Texture key={name} name={name}/>)}</div><div className="xp-wrap"><div className="xp-hero-copy"><h1>Cada visita ilumina<br/>uma parte da história.</h1><p>Escolha entre uma primeira descoberta, uma jornada aprofundada ou uma noite memorável sobre o Mediterrâneo.</p></div><div className="xp-hero-photo"><img src={image('PlaceholderHeroExperiencias')} alt="Interior de Pharos"/></div></div></section>
<section className="xp-packages" id="pacotes"><Texture name="BackgroundTextureReusoPassadoEPresente"/><div className="xp-wrap"><span className="xp-label">02 · Escolha sua experiência</span><div className="xp-heading"><h2>Encontre o seu ritmo em Pharos.</h2><p>Todos os pacotes incluem acesso ao monumento e às áreas públicas.</p></div><div className="xp-cards">{packages.map(([title,photo,copy,meta,price],i)=><article className="xp-card" key={title}><img className="xp-card-photo" src={image(photo)} alt={title}/><img className="xp-wave" src={image('Vector',true)} alt=""/><div className="xp-card-copy"><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p><div className="xp-meta">{meta}<span className="xp-mobile-price"> · €{price}</span></div><div className="xp-price">A partir de €{price}</div><Link className="button button-small" href={`/experiencias/${['visita-essencial','jornada-historica','pharos-por-do-sol'][i]}`}>Ver detalhes <ArrowRight size={14}/></Link></div></article>)}</div></div></section>
<section className="xp-compare"><Texture name="BackgroundTextureReusoReconstrucao"/><div className="xp-wrap"><span className="xp-label">03 · Compare os pacotes</span><h2>O que está incluído.</h2><div className="xp-table-scroll" role="region" aria-label="Comparação de experiências: deslize para os lados" tabIndex={0}><table className="xp-table"><thead><tr><th aria-label="Inclusões"/><th>Essencial</th><th>Histórica</th><th>Pôr do sol</th></tr></thead><tbody>{rows.map(([title,...values])=><tr key={title}><th scope="row">{title}</th>{values.map((v,i)=><td key={i} data-label={packages[i][0]}><span aria-label={v==='●'?'Incluído':'Não incluído'} className={v==='●'?'xp-included':''}>{v}</span></td>)}</tr>)}</tbody></table></div></div></section>
<section className="xp-info"><Texture name="BackgroundTextureReusoExperiencias"/><div className="xp-wrap"><span className="xp-label">04 · Antes de escolher</span><h2>Informações para planejar.</h2><div className="xp-info-grid">{information.map(([title,copy])=><article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
<section className="xp-ending"><img className="xp-ending-photo" src={image('PlaceholderAreaOrganicaDeImagem')} alt="Pharos ao entardecer"/><div className="xp-wrap"><span className="xp-label">05 · Sua visita começa aqui</span><h2>Já sabe como quer viver esta história?</h2><p>Escolha uma experiência para conferir datas, horários e disponibilidade.</p><a className="button button-large" href="#pacotes">Escolher experiência →</a></div><Footer/></section></main></PageEntrance>}
