'use client';
import Link from 'next/link';
import ConfirmationMark from './ConfirmationMark';
import {enhance} from './HomeEntrance';
import {useEffect,useRef,useState} from 'react';
import {experienceOptions} from '@/lib/experiences';
import {useBooking,visitors,bookingTotal,extras} from '@/components/Booking';
const asset=(n:string)=>`/images/tela8-img${n}.svg`;
export default function ConfirmationContent(){const [booking,,ready]=useBooking();const [open,setOpen]=useState(false);const closeRef=useRef<HTMLButtonElement>(null);const triggerRef=useRef<HTMLButtonElement>(null);
useEffect(()=>{if(!open)return;closeRef.current?.focus();const previous=document.body.style.overflow;document.body.style.overflow='hidden';const keydown=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false);if(e.key==='Tab'){e.preventDefault();closeRef.current?.focus()}};document.addEventListener('keydown',keydown);return()=>{document.body.style.overflow=previous;document.removeEventListener('keydown',keydown);triggerRef.current?.focus()}},[open]);
return enhance(<><img className="confirmation-landscape" src="/images/tela8-imgImagemConfirmacao.webp" alt="Farol de Alexandria visto da margem rochosa ao pôr do sol"/><div className="confirmation-shade"/><div className="confirmation-frame" aria-hidden="true"><img className="frame-main" src={asset('Vector')}/><img className="frame-inner" src={asset('Vector1')}/><img className="frame-main" src={asset('Vector2')}/><img className="frame-left" src={asset('Frame49')}/><img className="frame-right" src={asset('Frame50')}/>{['top','bottom','left','right'].map(side=><img key={side} className={`frame-dot ${side}`} src={asset('Vector3')}/>)}</div><div className="confirmation-content"><div className="confirmation-symbol" aria-hidden="true"><ConfirmationMark/></div><span className="eyebrow">08 · Reserva {ready&&booking.confirmed?'confirmada':'demonstrativa'}</span><h1>Sua visita a Pharos está confirmada.</h1><p className="confirmation-description">Sua reserva demonstrativa está pronta. Em uma reserva real, os detalhes e as orientações de embarque seriam enviados por e-mail.</p><section className="confirmation-receipt" id="comprovante" aria-label="Comprovante demonstrativo"><span className="booking-panel-label">Código da reserva</span><div className="confirmation-code">PHA-1828-0918</div><dl><div><dt>{experienceOptions[booking.experience].title}</dt><dd>{booking.date} · {booking.time}</dd></div><div><dt>Visitantes</dt><dd>{visitors(booking)}</dd></div><div><dt>Local de encontro</dt><dd>Terminal de Qaitbay</dd></div></dl></section><div className="confirmation-actions"><button ref={triggerRef} className="button button-large" onClick={()=>setOpen(true)}>Ver minha reserva →</button><Link className="button button-large secondary" href="/">Voltar ao início →</Link></div></div>{open&&<div className="reservation-modal-backdrop" onClick={()=>setOpen(false)}><section className="reservation-modal" role="dialog" aria-modal="true" aria-labelledby="reservation-title" onClick={e=>e.stopPropagation()}><button className="reservation-modal-close" ref={closeRef} aria-label="Fechar reserva" onClick={()=>setOpen(false)}>×</button><h2 id="reservation-title">Sua reserva demonstrativa</h2><p>PHA-1828-0918 · {experienceOptions[booking.experience].title}</p><p>{booking.date} · {booking.time}<br/>{visitors(booking)}</p><p>{booking.extras.length?booking.extras.map(id=>extras.find(e=>e.id===id)?.label).join(' · '):'Sem adicionais'}<br/>Total simulado: €{bookingTotal(booking)}</p><p>Encontro no terminal marítimo de Qaitbay, 30 minutos antes da sessão.</p><p>Este é um projeto de portfólio: nenhum pagamento, reserva real ou envio de e-mail foi realizado.</p></section></div>}</>)}
