"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

type Language = "pt" | "en";
const copy:Record<string,string>={
"História":"History","Experiências":"Experiences","Planeje sua visita":"Plan your visit","Reservar":"Book now","Dúvidas frequentes":"Frequently asked questions","Abrir menu":"Open menu","Fechar menu":"Close menu","Menu de navegação":"Navigation menu",
"Projeto conceitual":"Concept project","Uma Alexandria imaginada.":"An imagined Alexandria.","Este site foi criado para fins de portfólio. Reservas e pagamentos são demonstrativos; as imagens foram produzidas com inteligência artificial.":"This website was created as a portfolio project. Bookings and payments are demonstrations; the images were produced with artificial intelligence.","Explorar o projeto":"Explore the project",
"DOIS MILÊNIOS":"TWO MILLENNIA","A maravilha que guiou o mundo agora recebe você.":"The wonder that guided the world now welcomes you.","RESERVAR SUA VISITA":"BOOK YOUR VISIT","O HORIZONTE REACENDE":"THE HORIZON SHINES AGAIN","Alexandria · Egito":"Alexandria · Egypt","Mediterrâneo Oriental":"Eastern Mediterranean",
"PASSADO E PRESENTE":"PAST AND PRESENT","Uma maravilha reconstruída.":"A wonder rebuilt.","Erguido no século III a.C., o Farol de Alexandria guiou navegantes por mais de mil anos. Agora, evidências arqueológicas, engenharia contemporânea e uma ambição coletiva tornam possível vê-lo novamente no horizonte.":"Built in the 3rd century BC, the Lighthouse of Alexandria guided sailors for over a thousand years. Now, archaeological evidence, contemporary engineering and a collective ambition make it possible to see it on the horizon once again.","CONHEÇA A HISTÓRIA COMPLETA":"DISCOVER THE FULL STORY",
"POR DENTRO DO ÍCONE":"INSIDE THE ICON","Explore o Farol.":"Explore the Lighthouse.","Quatro níveis revelam a ciência, a história e a paisagem de Pharos.":"Four levels reveal the science, history and landscape of Pharos.","MIRANTE":"OBSERVATION DECK","O Mediterrâneo em 360°":"The Mediterranean in 360°","CÂMARA DA LUZ":"LIGHT CHAMBER","Ciência e navegação":"Science and navigation","GALERIAS":"GALLERIES","Coleções arqueológicas":"Archaeological collections","BASE MONUMENTAL":"MONUMENTAL BASE","A chegada a Pharos":"Arrival at Pharos","EXPLORE SUA ARQUITETURA":"EXPLORE ITS ARCHITECTURE",
"Escolha como viver esta história.":"Choose how to experience this story.","Três maneiras de conhecer Pharos, cada visita criada para um ritmo e uma curiosidade diferente.":"Three ways to discover Pharos, each designed for a different pace and curiosity.","VISITA ESSENCIAL":"ESSENTIAL VISIT","JORNADA HISTÓRICA":"HISTORICAL JOURNEY","PHAROS AO PÔR DO SOL":"PHAROS AT SUNSET","VER DETALHES":"VIEW DETAILS",
"Conheça Pharos no seu ritmo: galerias, exposição histórica e mirante em um percurso livre.":"Discover Pharos at your own pace: galleries, historical exhibition and observation deck in a self-guided route.","Uma visita guiada pelas camadas arqueológicas, reconstrução e memórias do farol.":"A guided visit through the archaeological layers, reconstruction and memories of the lighthouse.","Suba ao mirante ao entardecer e desfrute gastronomia mediterrânea e iluminação noturna.":"Reach the observation deck at dusk and enjoy Mediterranean cuisine and the lighthouse after dark.",
"INFORMAÇÕES PRÁTICAS":"PRACTICAL INFORMATION","Planeje sua visita.":"Plan your visit.","LOCALIZAÇÃO":"LOCATION","HORÁRIOS":"OPENING HOURS","COMO CHEGAR":"GETTING HERE","ACESSIBILIDADE":"ACCESSIBILITY","IDIOMAS":"LANGUAGES","FAMÍLIAS":"FAMILIES","PERGUNTAS FREQUENTES":"FREQUENTLY ASKED QUESTIONS",
"A LUZ VOLTOU A ALEXANDRIA":"THE LIGHT HAS RETURNED TO ALEXANDRIA","Faça parte deste retorno.":"Be part of its return.","Reserve sua visita e contemple novamente uma das grandes maravilhas da humanidade.":"Book your visit and witness one of humanity’s great wonders once again.","RESERVAR VISITA":"BOOK A VISIT","VER EXPERIÊNCIAS":"VIEW EXPERIENCES",
"02 · PASSADO E PRESENTE":"02 · PAST AND PRESENT","03 · POR DENTRO DO ÍCONE":"03 · INSIDE THE ICON","04 · EXPERIÊNCIAS":"04 · EXPERIENCES","05 · INFORMAÇÕES PRÁTICAS":"05 · PRACTICAL INFORMATION","06 · A LUZ VOLTOU A ALEXANDRIA":"06 · THE LIGHT HAS RETURNED TO ALEXANDRIA",
"Ilha de Pharos · Porto Oriental":"Pharos Island · Eastern Harbour","Alexandria, Egito":"Alexandria, Egypt","Todos os dias · 09h–22h":"Every day · 9am–10pm","Última entrada às 20h30":"Last admission at 8:30pm","Shuttle marítimo a cada 20 min":"Sea shuttle every 20 minutes","Saídas do Terminal Qaitbay":"Departures from Qaitbay Terminal","Percurso integral acessível":"Fully accessible route","Elevadores e apoio mediante solicitação":"Lifts and assistance on request","Árabe, inglês, francês e português":"Arabic, English, French and Portuguese","Audioguia em 12 idiomas":"Audio guide in 12 languages","Entrada gratuita até 11 anos":"Free admission for children under 12","Espaço família e guarda-volumes":"Family area and cloakroom","ILHA DE PHAROS · PORTO ORIENTAL · ALEXANDRIA, EGITO":"PHAROS ISLAND · EASTERN HARBOUR · ALEXANDRIA, EGYPT",
"INAUGURAÇÃO":"OPENING","NO HORIZONTE":"ON THE HORIZON","ALTURA RECONSTRUÍDA":"REBUILT HEIGHT","ABERTURA PREVISTA":"PLANNED OPENING","Anterior":"Previous","Próxima":"Next",
"Cada visita ilumina uma parte da história.":"Each visit illuminates a part of history.","Escolha entre uma primeira descoberta, uma jornada aprofundada ou uma noite memorável sobre o Mediterrâneo.":"Choose between a first discovery, an in-depth journey or a memorable night above the Mediterranean.","Erguido para guiar. Reconstruído para permanecer.":"Built to guide. Rebuilt to endure.",
"Jornada histórica.":"Historical journey.","Visita essencial.":"Essential visit.","Pharos ao Pôr do Sol.":"Pharos at sunset.","ESCOLHER DATA":"CHOOSE A DATE",
"Escolha a data e os visitantes.":"Choose a date and visitors.","Defina quando deseja visitar Pharos e informe quem estará com você.":"Choose when you wish to visit Pharos and tell us who will join you.","Escolha uma sessão":"Choose a session","VISITANTES":"VISITORS","Adultos":"Adults","Jovens · 12–17":"Young people · 12–17","Crianças · até 11":"Children · under 12","Gratuito":"Free","SUA EXPERIÊNCIA":"YOUR EXPERIENCE","CONTINUAR":"CONTINUE",
"Ingressos e adicionais.":"Tickets and extras.","Personalize a experiência antes de revisar sua reserva.":"Personalise your experience before reviewing your booking.","INGRESSOS":"TICKETS","ADICIONAIS":"EXTRAS","Audioguia":"Audio guide","Degustação ampliada":"Extended tasting","Livro ilustrado de Pharos":"Illustrated Pharos book","REVISAR RESERVA":"REVIEW BOOKING",
"Revise sua reserva.":"Review your booking.","Confira os dados abaixo antes de confirmar sua experiência.":"Check the information below before confirming your experience.","EXPERIÊNCIA":"EXPERIENCE","DATA E VISITANTES":"DATE AND VISITORS","EDITAR":"EDIT","ENCONTRO":"MEETING POINT","RESUMO DO VALOR":"PRICE SUMMARY","Ingressos":"Tickets","CONFIRMAR RESERVA":"CONFIRM BOOKING",
"Sua visita a Pharos está confirmada.":"Your visit to Pharos is confirmed.","RESERVA CONFIRMADA":"BOOKING CONFIRMED","CÓDIGO DA RESERVA":"BOOKING CODE","LOCAL DE ENCONTRO":"MEETING POINT","VER MINHA RESERVA":"VIEW MY BOOKING","VOLTAR AO INÍCIO":"BACK TO HOME","Perguntas frequentes.":"Frequently asked questions.","Tudo o que você precisa saber antes de visitar Pharos.":"Everything you need to know before visiting Pharos.",
"Ilha de Pharos · Porto Oriental Alexandria, Egito":"Pharos Island · Eastern Harbour Alexandria, Egypt","Todos os dias · 09h–22h Última entrada às 20h30":"Every day · 9am–10pm Last admission at 8:30pm","Shuttle marítimo a cada 20 min Saídas do Terminal Qaitbay":"Sea shuttle every 20 minutes Departures from Qaitbay Terminal","Percurso integral acessível Elevadores e apoio mediante solicitação":"Fully accessible route Lifts and assistance on request","Árabe, inglês, francês e português Audioguia em 12 idiomas":"Arabic, English, French and Portuguese Audio guide in 12 languages","Entrada gratuita até 11 anos Espaço família e guarda-volumes":"Free admission for children under 12 Family area and cloakroom",
"A trajetória de Pharos atravessa impérios, terremotos e séculos de ausência. Agora, arqueologia e engenharia devolvem sua luz ao Mediterrâneo.":"The story of Pharos crosses empires, earthquakes and centuries of absence. Now, archaeology and engineering return its light to the Mediterranean.","02 · LINHA DO TEMPO":"02 · TIMELINE","Do projeto de Sóstrato ao novo horizonte.":"From Sostratus’ design to a new horizon.","TERREMOTOS":"EARTHQUAKES","NOVA FUNÇÃO":"A NEW PURPOSE","RECONSTRUÇÃO":"RECONSTRUCTION","UMA LUZ RETORNA":"A LIGHT RETURNS","O farol se torna referência de navegação e engenharia.":"The lighthouse becomes a landmark of navigation and engineering.","Abalos sucessivos comprometem sua estrutura.":"Successive earthquakes compromise its structure.","Suas pedras passam a integrar a fortaleza de Qaitbay.":"Its stones become part of Qaitbay Fortress.","O projeto contemporâneo começa sobre estudos arqueológicos.":"The contemporary project begins with archaeological studies.","Pharos reabre ao público e ao Mediterrâneo.":"Pharos reopens to the public and the Mediterranean.",
"03 · UM SÍMBOLO DO MUNDO ANTIGO":"03 · A SYMBOL OF THE ANCIENT WORLD","Muito além de um farol.":"Far more than a lighthouse.","Uma obra que uniu ciência, comércio e imaginação às margens de uma das cidades mais cosmopolitas da Antiguidade.":"A landmark that united science, trade and imagination on the shores of one of antiquity’s most cosmopolitan cities.","como referência histórica":"as a historical landmark","de altura estimada":"estimated height","de arquitetura monumental":"of monumental architecture","04 · DESCOBERTAS ARQUEOLÓGICAS":"04 · ARCHAEOLOGICAL DISCOVERIES","As evidências que tornaram o retorno possível.":"The evidence that made its return possible.",
"05 · JUSTIFICATIVA DA RECONSTRUÇÃO":"05 · WHY REBUILD","Reconstruir sem apagar o tempo.":"Rebuilding without erasing time.","O novo Pharos não ocupa vestígios originais nem reivindica ser uma réplica arqueológica absoluta. É uma reconstrução crítica: fiel ao conhecimento disponível e transparente sobre cada decisão contemporânea.":"The new Pharos does not occupy original remains or claim to be an absolute archaeological replica. It is a critical reconstruction: faithful to available knowledge and transparent about every contemporary decision.","PESQUISA":"RESEARCH","REVERSIBILIDADE":"REVERSIBILITY","ACESSO PÚBLICO":"PUBLIC ACCESS","Decisões baseadas em iconografia, descrições e arqueologia.":"Decisions based on iconography, descriptions and archaeology.","Soluções modernas que preservam futuras interpretações.":"Modern solutions that preserve future interpretations.","Um monumento vivo, educativo e acessível.":"A living, educational and accessible monument.",
"06 · PASSADO E PRESENTE":"06 · PAST AND PRESENT","Onde termina a história e começa o presente.":"Where history ends and the present begins.","FIDELIDADE HISTÓRICA":"HISTORICAL FIDELITY","ADAPTAÇÕES MODERNAS":"MODERN ADAPTATIONS","TECNOLOGIA INVISÍVEL":"INVISIBLE TECHNOLOGY","Proporções gerais, organização em níveis, materiais minerais e presença da chama como símbolo.":"Overall proportions, tiered organisation, mineral materials and the flame as a symbol.","Estrutura reforçada, elevadores, rotas acessíveis, climatização, segurança e operação sustentável.":"Reinforced structure, lifts, accessible routes, climate control, safety and sustainable operation.","Sistemas contemporâneos integrados para não disputar atenção com a arquitetura.":"Contemporary systems integrated without competing with the architecture.",
"07 · ARQUITETURA INTERNA":"07 · INTERIOR ARCHITECTURE","Quatro níveis, uma jornada ascendente.":"Four levels, one ascending journey.","Recepção e introdução histórica":"Reception and historical introduction","Coleções e vestígios arqueológicos":"Collections and archaeological remains","Ciência, navegação e tecnologia":"Science, navigation and technology","08 · CONTINUE A JORNADA":"08 · CONTINUE THE JOURNEY","Agora, conheça Pharos por dentro.":"Now, discover Pharos from within.","A história está de volta. Escolha como deseja conhecê-la e prepare sua visita a Pharos.":"History has returned. Choose how you wish to discover it and prepare your visit to Pharos."
};
const LanguageContext=createContext<{language:Language;setLanguage:(language:Language)=>void}>({language:"pt",setLanguage:()=>{}});
const reverse=Object.fromEntries(Object.entries(copy).map(([pt,en])=>[en,pt]));
const copyInsensitive=new Map(Object.keys(copy).map(key=>[key.toLocaleLowerCase("pt-BR"),key]));
const reverseInsensitive=new Map(Object.keys(reverse).map(key=>[key.toLocaleLowerCase("en"),key]));
function translated(text:string,language:Language){const raw=text.trim();const key=language==="en"?(copyInsensitive.get(raw.toLocaleLowerCase("pt-BR"))??raw):(reverseInsensitive.get(raw.toLocaleLowerCase("en"))??raw);let value=language==="en"?copy[key]:reverse[key];if(!value&&language==="en"){value=raw.replace(/RESERVA \/ ETAPA (\d) DE 4/i,"BOOKING / STEP $1 OF 4").replace(/(\d+) adultos?/i,"$1 adults").replace(/(\d+) jovens?/i,"$1 young people").replace(/(\d+) crianças?/i,"$1 children")}if(!value)return text;return `${text.match(/^\s*/)?.[0]??""}${value}${text.match(/\s*$/)?.[0]??""}`}
function translateAnimatedElement(element:HTMLElement,language:Language){
 const spans=Array.from(element.querySelectorAll<HTMLElement>(":scope .home-generated-word"));
 if(!spans.length)return;
 const current=spans.map(span=>span.textContent?.trim()).filter(Boolean).join(" ");
 const original=element.dataset.i18nOriginal??copyInsensitive.get(current.toLocaleLowerCase("pt-BR"))??reverse[reverseInsensitive.get(current.toLocaleLowerCase("en"))??""];
 if(!original)return;
 element.dataset.i18nOriginal=original;
 const target=language==="en"?copy[original]:original;
 if(!target)return;
 const words=target.split(/\s+/);
 spans.forEach((span,index)=>{span.textContent=index===spans.length-1?words.slice(index).join(" "):(words[index]??"")});
}
export function LanguageProvider({children}:{children:React.ReactNode}){
 const[language,setLanguageState]=useState<Language>("pt");
 useEffect(()=>{if(localStorage.getItem("pharos-language")==="en")setLanguageState("en")},[]);
 useEffect(()=>{document.documentElement.lang=language==="pt"?"pt-BR":"en";const apply=(root:Node)=>{const animated=root instanceof HTMLElement?[root,...Array.from(root.querySelectorAll<HTMLElement>("[data-home-reveal='text']"))]:Array.from((root as ParentNode).querySelectorAll?.<HTMLElement>("[data-home-reveal='text']")??[]);animated.forEach(element=>translateAnimatedElement(element,language));const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node:Node|null;while((node=walker.nextNode())){const text=node as Text;if(text.parentElement?.classList.contains("home-generated-word"))continue;text.data=translated(text.data,language)}const elements=root instanceof Element?[root,...Array.from(root.querySelectorAll("[aria-label],[title]"))]:Array.from((root as ParentNode).querySelectorAll?.("[aria-label],[title]")??[]);for(const el of elements)for(const name of ["aria-label","title"]){const current=el.getAttribute(name);if(current)el.setAttribute(name,translated(current,language))}};apply(document.body);const observer=new MutationObserver(records=>records.forEach(record=>record.addedNodes.forEach(apply)));observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect()},[language]);
 const value=useMemo(()=>({language,setLanguage:(next:Language)=>{localStorage.setItem("pharos-language",next);setLanguageState(next)}}),[language]);return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}
export function LanguageSwitcher({mobile=false}:{mobile?:boolean}){const{language,setLanguage}=useContext(LanguageContext);return <div className={`language-switcher${mobile?" language-switcher-mobile":""}`} role="group" aria-label={language==="pt"?"Selecionar idioma":"Select language"}><button type="button" aria-pressed={language==="pt"} onClick={()=>setLanguage("pt")}>PT</button><span aria-hidden="true"/><button type="button" aria-pressed={language==="en"} onClick={()=>setLanguage("en")}>EN</button></div>}
