import Image from "next/image";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { Header } from "@/components/SiteChrome";
import { LocalizedText } from "@/components/LanguageSwitcher";
import "./home-refinements.css";
import HomeHistoryCarousel from "@/components/HomeHistoryCarousel";
import HomeEntrance from "@/components/HomeEntrance";
import PortfolioNotice from "@/components/PortfolioNotice";

const historyPhotos = [
  ["/images/home-carousel.webp", "Visitantes nas galerias de Pharos"],
  ["/images/pharos-chegada-v2.webp", "Chegada à base monumental de Pharos"],
  ["/images/home-card-2.webp", "Visita às coleções históricas do farol"],
  ["/images/pharos-camara-luz-v2.webp", "A Câmara da Luz ao entardecer"],
  ["/images/pharos-estudo-historico-v2.webp", "Equipe estudando a reconstrução de Pharos"],
  ["/images/tela2-imgPlaceholderVestigiosSubmersos.webp", "Blocos monumentais submersos no Porto Oriental"],
  ["/images/tela2-imgPlaceholderPesquisaArqueologica.webp", "Levantamentos e pesquisa arqueológica de Pharos"],
  ["/images/tela3-imgPlaceholderHeroExperiencias.webp", "Percurso dos visitantes pelo interior do farol"],
  ["/images/jornada-historica-card-v2.webp", "Guia apresentando a maquete de Pharos"],
  ["/images/tela4-imgImagemDoCarrosselSubstituirFill.webp", "Mirante e degustação ao anoitecer"],
];

const practical=[["Localização","Ilha de Pharos · Porto Oriental|Alexandria, Egito"],["Horários","Todos os dias · 09h–22h|Última entrada às 20h30"],["Como chegar","Shuttle marítimo a cada 20 min|Saídas do Terminal Qaitbay"],["Acessibilidade","Percurso integral acessível|Elevadores e apoio mediante solicitação"],["Idiomas","Árabe, inglês, francês e português|Audioguia em 12 idiomas"],["Famílias","Entrada gratuita até 11 anos|Espaço família e guarda-volumes"]];
const cards=[["01","VISITA ESSENCIAL","1H30 · €29","Conheça Pharos no seu ritmo: galerias, exposição histórica e mirante em um percurso livre.","/images/visita-essencial-card-v2.webp","/experiencias/visita-essencial"],["02","JORNADA HISTÓRICA","2H30 · €49","Uma visita guiada pelas camadas arqueológicas, reconstrução e memórias do farol.","/images/home-card-2.webp","/experiencias/jornada-historica"],["03","PHAROS AO PÔR DO SOL","3H · €89","Suba ao mirante ao entardecer e desfrute gastronomia mediterrânea e iluminação noturna.","/images/pharos-por-do-sol-card-v2.webp","/experiencias/pharos-por-do-sol"]];
export default function Home(){return <HomeEntrance><main className="home-final"><Header/><PortfolioNotice/>
<section className="home-hero"><Image className="hero-bg-art" src="/images/figma-home-hero-bg.svg" alt="" fill priority/><Image className="hero-moon" src="/images/hero-moon.svg" alt="" width={520} height={520}/><div className="hero-light-art" aria-hidden="true"><img className="hero-light-right" src="/images/home-imgVector.svg" alt=""/><img className="hero-light-left" src="/images/home-imgVector1.svg" alt=""/></div><Image className="hero-tower" src="/images/hero-lighthouse.svg" alt="Ilustração do Farol de Alexandria reconstruído" width={500} height={800} priority/><Image className="hero-sea" src="/images/hero-sea.svg" alt="" width={1440} height={240}/><div className="hero-primary"><h1>DOIS MILÊNIOS</h1><p>A maravilha que guiou o mundo<br/>agora recebe você.</p><Link className="button button-large" href="/reserva/data">Reservar sua visita <ArrowRight size={17}/></Link></div><h2 className="hero-secondary">O HORIZONTE<br/>REACENDE</h2><div className="hero-coordinates"><span>31.2135° N<br/>29.8853° E</span><span><LocalizedText pt="Alexandria · Egito" en="Alexandria · Egypt"/><br/><LocalizedText pt="Mediterrâneo Oriental" en="Eastern Mediterranean"/></span></div></section>
<section id="passado" className="home-history"><Image className="section-art" src="/images/home-history-texture.svg" alt="" fill/><div className="home-history-copy"><span className="eyebrow">02 · PASSADO E PRESENTE</span><h2>Uma maravilha<br/>reconstruída.</h2><p>Erguido no século III a.C., o Farol de Alexandria guiou navegantes por mais de mil anos. Agora, evidências arqueológicas, engenharia contemporânea e uma ambição coletiva tornam possível vê-lo novamente no horizonte.</p><Link className="text-link" href="/historia">Conheça a história completa <ArrowRight size={14}/></Link></div><HomeHistoryCarousel photos={historyPhotos}/><div className="history-facts">{[["c. 280 a.C.","INAUGURAÇÃO"],["+1.500 anos","NO HORIZONTE"],["130 metros","ALTURA RECONSTRUÍDA"],["2028","ABERTURA PREVISTA"]].map(x=><div key={x[0]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div></section>
<section className="home-explore"><Image className="section-art" src="/images/home-explore-texture.svg" alt="" fill/><span className="eyebrow">03 · POR DENTRO DO ÍCONE</span><div className="explore-title"><h2>Explore o Farol.</h2><p>Quatro níveis revelam a ciência, a história e a paisagem de Pharos.</p></div><div className="explore-body"><Image src="/images/home-cutaway.svg" alt="Corte arquitetônico dos quatro níveis de Pharos" width={420} height={662}/><div className="level-list">{[["01","MIRANTE","O Mediterrâneo em 360°"],["02","CÂMARA DA LUZ","Ciência e navegação"],["03","GALERIAS","Coleções arqueológicas"],["04","BASE MONUMENTAL","A chegada a Pharos"]].map(x=><article key={x[0]}><span>{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}<Link className="text-link" href="/historia">Explore sua arquitetura <ArrowRight size={14}/></Link></div></div></section>
<section className="home-experiences"><Image className="section-art" src="/images/home-experiences-texture.svg" alt="" fill/><span className="eyebrow">04 · EXPERIÊNCIAS</span><div className="experience-heading"><h2>Escolha como viver<br/>esta história.</h2><p>Três maneiras de conhecer Pharos, cada visita criada para um ritmo e uma curiosidade diferente.</p></div><div className="home-card-grid">{cards.map(c=><article className="home-card" key={c[0]}><div className="home-card-image"><Image src={c[4]} alt={`Imagem da experiência ${c[1]}`} fill sizes="(max-width: 767px) 84vw, 400px"/></div><div className="home-card-copy"><span>{c[0]} · {c[2]}</span><h3>{c[1]}</h3><p>{c[3]}</p><Link className="button button-small" href={c[5]}>Ver detalhes <ArrowRight size={14}/></Link></div></article>)}</div></section>
<section className="home-practical"><Image className="map-art" src="/images/home-map.webp" alt="" fill/><span className="eyebrow">05 · INFORMAÇÕES PRÁTICAS</span><h2>Planeje sua visita.</h2><div className="navigation-compass" aria-hidden="true"><img className="compass-orbits" src="/images/home-imgGroup.svg" alt=""/><span className="compass-north">N</span><span className="compass-south">S</span><span className="compass-east">L</span><span className="compass-west">O</span><img className="compass-wave" src="/images/home-imgVector10.svg" alt=""/></div><div className="practical-list">{practical.map(x=><article key={x[0]}><h3>{x[0]}</h3><p>{x[1].split("|").map(y=><span key={y}>{y}</span>)}</p></article>)}<Link className="text-link" href="/duvidas-frequentes">Perguntas frequentes <ArrowRight size={14}/></Link></div></section>
<section className="home-closing"><Image src="/images/home-cta-v2.webp" alt="Visitantes no interior monumental de Pharos" fill sizes="100vw"/><div className="home-original-frame" aria-hidden="true"><img className="frame-outer" src="/images/home-imgVector11.svg" alt=""/><img className="frame-inner" src="/images/home-imgVector12.svg" alt=""/><img className="frame-corners" src="/images/home-imgVector13.svg" alt=""/><img className="frame-left" src="/images/home-imgFrame49.svg" alt=""/><img className="frame-right" src="/images/home-imgFrame50.svg" alt=""/><img className="frame-top" src="/images/home-imgVector14.svg" alt=""/><img className="frame-bottom" src="/images/home-imgVector14.svg" alt=""/></div><span className="closing-label">06 · A LUZ VOLTOU A ALEXANDRIA</span><div className="closing-copy"><h2>Faça parte<br/>deste retorno.</h2><p>Reserve sua visita e contemple novamente uma das grandes maravilhas da humanidade.</p><div><Link className="button button-large" href="/reserva/data">Reservar visita <ArrowRight size={17}/></Link><Link className="text-link" href="/experiencias">Ver experiências <ArrowRight size={17}/></Link></div></div><footer className="closing-footer"><Link className="footer-faq" href="/duvidas-frequentes">Dúvidas frequentes</Link><span>© 2028 PHAROS / ALEXANDRIA · @PHAROS.ALEXANDRIA</span><span>ILHA DE PHAROS · PORTO ORIENTAL · ALEXANDRIA, EGITO</span><span className="home-social-icons">{[["Instagram","imgSocialInstagram"],["X","imgSocialXOfficial"],["LinkedIn","imgSocialLinkedIn"],["YouTube","imgSocialYouTube"]].map(([name,asset])=><img key={name} src={`/images/home-${asset}.svg`} alt={name} width={name==="YouTube"?20:18} height={18}/>)}</span></footer></section>
</main></HomeEntrance>}
